### ISSUE TITLE
Ability to fully freeze memory addresses

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/Genesis-Plus-GX#2]
Camhack needs the world to remain in the non-runahead state, so all objects need to have their memory values frozen while we're forcing the camera to go to where the character is.

If the character is way ahead, it takes dozens of invisible frames, because in genesis Sonic games we can't just poke camera to jump to where we need it, it has to be moving there gradually or everything breaks.

So while all this is happening, we need to ensure the world remains frozen so the camera doesn't display things in different places by the time it gets there. Then this could be exposed as a gpgx-exclusive lua function.

My idea has always been having internal memory hooks on the addresses we need to freeze, and on every write occurring from the core, we'd write it back to what it's frozen at immediately.

**Comment by SergioMartin86** [comment]
This is resolved, I suppose?

**Comment by vadosnaprimer** [comment]
Yeah, I'll get back to minor tweaks when I update the camhack scripts. Thanks!
