### ISSUE TITLE
Savestate integrity: SMS background colour incorrect on loadstate

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/Genesis-Plus-GX#5]
Originally reported by @ScHlAuChi on Discord. There doesn't appear to be a related issue filed upstream, nor in BizHawk's tracker (this core is new after all).

Repro:
1. Load SMS *Asterix and the Secret Mission* `SHA1:DE6A32A548551553A4B3AE332F4BF98ED22D8AB5` in EmuHawk
	- Also affects the Game Gear port `SHA1:8AB4EA406A0503B09C1BD89E3217C5735B36EBED`, which will show the incorrect behaviour as early as frame ~50—though I had to hardcode GPGX for GG roms as the core preference wasn't being respected.
1. Advance to the start of gameplay (frame ~500 if you spam B1 through the menus)
1. Savestate
1. Loadstate
1. Observe sky is lime green instead of blue (if you have "Use custom backdrop color" enabled, it will be magenta or whatever you've set that to be)
	- On the GG port it's olive green, and the custom colour will override that also.

Affects:
- Genplus-gx in EmuHawk `master` at https://github.com/TASEmulators/BizHawk/commit/ee0c0a80d09974fd0d89caaf56b2bd7b32b270ba

Doesn't affect:
- SMSHawk in EmuHawk `master` at https://github.com/TASEmulators/BizHawk/commit/ee0c0a80d09974fd0d89caaf56b2bd7b32b270ba

**Comment by Morilli** [comment]
Confirmed fixed for me with [9ce41a2](https://github.com/TASEmulators/BizHawk/commit/9ce41a2a88dc3a98cfc69da53f4ddeb90dcf7b02).
